---
- name: get gpg key
  shell: apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  become: yes
  become_user: root
- name: add docker repos to apt
  template: >
    src=docker.list.j2
    dest=/etc/apt/sources.list.d/docker.list
    owner=root
    group=staff
    mode=644
  become: yes
  become_user: root
- name: apt-get update
  apt: update_cache=yes
  become: yes
  become_user: root
- name: apt-get install docker-engine
  apt: name=docker-engine state=latest
  become: yes
  become_user: root
- name: start docker
  service: name=docker state=started
  become: yes
  become_user: root
